### ISSUE TITLE
Unable to open .k.zip files on Mac

### ISSUE THREAD

**Issue by chbehrens** [knossos-project/knossos#94] opened 2015-02-11 10:58 UTC
Using Knossos on OS X it is not possible to open .k.zip files, Skeletons can only be loaded from .nml files

**Comment by Optiligence** [comment] 2015-02-13 13:57
as a workaround you can use drag’n’drop

**Comment by Optiligence** [comment] 2015-02-13 14:00
i’m closing this as a duplicate of #98 which is more detailed

**Closed by Optiligence** 2015-02-13 14:00 UTC
Labels: bug, duplicate
